{\rtf1\ansi\ansicpg936\cocoartf1404\cocoasubrtf340
{\fonttbl\f0\fnil\fcharset0 Consolas;}
{\colortbl;\red255\green255\blue255;\red14\green14\blue14;\red242\green239\blue236;}
\paperw11900\paperh16840\margl1440\margr1440\vieww10800\viewh8400\viewkind0
\deftab720
\pard\pardeftab720\sl576\partightenfactor0

\f0\fs32 \cf2 \cb3 \expnd0\expndtw0\kerning0
base: /lxm20819\
}